name: path_project
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_secure_storage: 5.0.2
  flutter_riverpod: 2.0.0-dev.3
  retrofit: 3.0.1+1
  dartz: ^0.10.1
  freezed_annotation: 2.0.1
  device_info_plus: 3.2.3
  package_info_plus: 1.4.2
  version: ^2.0.0
  dio: ^4.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.1.10
  retrofit_generator: 4.0.1
  freezed: 2.0.2
  flutter_lints: ^1.0.0
  json_serializable: 6.1.6

flutter:

  uses-material-design: true
